Unit tests of generic-fast-serializer on specific record with enums. For now marked as ignored due to:
class com.linkedin.avro.fastserde.generated.avro.JustSimpleEnum cannot be cast to class org.apache.avro.generic.GenericData$EnumSymbol (com.linkedin.avro.fastserde.generated.avro.JustSimpleEnum and org.apache.avro.generic.GenericData$EnumSymbol are in unnamed module of loader 'app')
java.lang.ClassCastException: class com.linkedin.avro.fastserde.generated.avro.JustSimpleEnum cannot be cast to class org.apache.avro.generic.GenericData$EnumSymbol (com.linkedin.avro.fastserde.generated.avro.JustSimpleEnum and org.apache.avro.generic.GenericData$EnumSymbol are in unnamed module of loader 'app')
	at com.linkedin.avro.fastserde.generated.serialization.AVRO_1_10.FastSerdeEnums_GenericSerializer_957378572.serializeFastSerdeEnums0(FastSerdeEnums_GenericSerializer_957378572.java:26)
	at com.linkedin.avro.fastserde.generated.serialization.AVRO_1_10.FastSerdeEnums_GenericSerializer_957378572.serialize(FastSerdeEnums_GenericSerializer_957378572.java:19)
	at com.linkedin.avro.fastserde.generated.serialization.AVRO_1_10.FastSerdeEnums_GenericSerializer_957378572.serialize(FastSerdeEnums_GenericSerializer_957378572.java:11)
	at com.linkedin.avro.fastserde.FastGenericSerializerGeneratorTest.dataAsBinaryDecoder(FastGenericSerializerGeneratorTest.java:615)
	at com.linkedin.avro.fastserde.FastGenericSerializerGeneratorTest.dataAsBinaryDecoder(FastGenericSerializerGeneratorTest.java:604)
	at com.linkedin.avro.fastserde.FastGenericSerializerGeneratorTest.shouldWriteSpecificRecordWithEnums(FastGenericSerializerGeneratorTest.java:192)